# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='field_1',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='field_2',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='field_3',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
